# -*- coding: utf-8 -*-
"""Layers and activation functions performance .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Hcsvc9FWvxIHfLJthOQAC4d_Fx2EZqz
"""

import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch.utils.data import TensorDataset, DataLoader

# Device config
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 1. Dataset
X, y = make_moons(n_samples=1000, noise=0.25, random_state=42)
X = StandardScaler().fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

X_train_tensor = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train_tensor = torch.tensor(y_train, dtype=torch.long).to(device)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32).to(device)
y_test_tensor = torch.tensor(y_test, dtype=torch.long).to(device)

train_loader = DataLoader(TensorDataset(X_train_tensor, y_train_tensor), batch_size=32, shuffle=True)

# 2. Flexible NN
class FlexibleNN(nn.Module):
    def __init__(self, input_dim, hidden_layers, activations, output_dim=2):
        super(FlexibleNN, self).__init__()
        layers = []
        in_dim = input_dim
        for h, act in zip(hidden_layers, activations):
            layers.append(nn.Linear(in_dim, h))
            if act == "relu":
                layers.append(nn.ReLU())
            elif act == "tanh":
                layers.append(nn.Tanh())
            elif act == "sigmoid":
                layers.append(nn.Sigmoid())
            elif act == "leakyrelu":
                layers.append(nn.LeakyReLU())
            in_dim = h
        layers.append(nn.Linear(in_dim, output_dim))  # output layer
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)

# 3. Training function
def train_model(hidden_layers, activations, epochs=30):
    model = FlexibleNN(2, hidden_layers, activations).to(device)
    optimizer = optim.Adam(model.parameters(), lr=0.01)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(epochs):
        for xb, yb in train_loader:
            optimizer.zero_grad()
            preds = model(xb)
            loss = criterion(preds, yb)
            loss.backward()
            optimizer.step()

    with torch.no_grad():
        preds = model(X_test_tensor).argmax(dim=1)
        acc = (preds == y_test_tensor).float().mean().item()
    return acc

# 4. Good experiments
good_experiments = [
    {"hidden_layers": [32], "activations": ["relu"]},
    {"hidden_layers": [32], "activations": ["tanh"]},
    {"hidden_layers": [64, 32], "activations": ["relu", "relu"]},
    {"hidden_layers": [64, 32], "activations": ["relu", "tanh"]},
    {"hidden_layers": [64, 32], "activations": ["tanh", "relu"]},
    {"hidden_layers": [128, 64, 32], "activations": ["relu", "relu", "relu"]},
    {"hidden_layers": [128, 64, 32], "activations": ["relu", "tanh", "relu"]},
    {"hidden_layers": [128, 64, 32], "activations": ["tanh", "relu", "tanh"]},
]

# 5. Run experiments
good_results = []
for exp in good_experiments:
    acc = train_model(exp["hidden_layers"], exp["activations"], epochs=30)
    good_results.append((exp, acc))

good_results

import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch.utils.data import TensorDataset, DataLoader

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Dataset (moons for non-linear separation)
X, y = make_moons(n_samples=1000, noise=0.25, random_state=42)
X = StandardScaler().fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

X_train_tensor = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train_tensor = torch.tensor(y_train, dtype=torch.long).to(device)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32).to(device)
y_test_tensor = torch.tensor(y_test, dtype=torch.long).to(device)

train_loader = DataLoader(TensorDataset(X_train_tensor, y_train_tensor), batch_size=32, shuffle=True)

# Flexible NN
class FlexibleNN(nn.Module):
    def __init__(self, input_dim, hidden_layers, activation="relu", output_dim=2):
        super(FlexibleNN, self).__init__()
        layers = []
        in_dim = input_dim
        for h in hidden_layers:
            layers.append(nn.Linear(in_dim, h))
            if activation == "relu":
                layers.append(nn.ReLU())
            elif activation == "tanh":
                layers.append(nn.Tanh())
            elif activation == "sigmoid":
                layers.append(nn.Sigmoid())
            in_dim = h
        layers.append(nn.Linear(in_dim, output_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)

# Training function
def train_model(hidden_layers, activation="relu", epochs=30):
    model = FlexibleNN(2, hidden_layers, activation).to(device)
    optimizer = optim.Adam(model.parameters(), lr=0.01)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(epochs):
        for xb, yb in train_loader:
            optimizer.zero_grad()
            preds = model(xb)
            loss = criterion(preds, yb)
            loss.backward()
            optimizer.step()

    with torch.no_grad():
        preds = model(X_test_tensor).argmax(dim=1)
        acc = (preds == y_test_tensor).float().mean().item()
    return acc

# Best combinations for 1 to 5 hidden layers
experiments = [
    {"layers": [32], "activation": "relu"},
    {"layers": [64, 32], "activation": "relu"},
    {"layers": [128, 64, 32], "activation": "relu"},
    {"layers": [256, 128, 64, 32], "activation": "sigmoid"},
    {"layers": [512, 256, 128, 64, 32], "activation": "relu"},
]

# Run experiments
results = []
for exp in experiments:
    acc = train_model(exp["layers"], activation=exp["activation"], epochs=30)
    results.append((exp["layers"], exp["activation"], acc))

# Show results
for r in results:
    print(f"Layers: {r[0]}, Activation: {r[1]}, Accuracy: {r[2]:.4f}")